# Configurations
title:            X맨
longtitle:        X맨이 운영하는 블로그
author:           엑스맨
email:            isthex00@gmail.com
description: >
  X맨이 운영하는 블로그랍니다.

version:          1.0
gitbook_version:  3.2.3

url:              'https://15inchnotebook.com'
baseurl:          '/jekyll-gitbook'
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
